# Generated by Django 5.0.6 on 2024-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto",
                    models.CharField(help_text="Maximo 25 caracteres", max_length=25),
                ),
                ("precio", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Gastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now=True)),
                ("detalle", models.CharField(max_length=30)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("GEN", "Generales"),
                            ("DIS", "Distribucion"),
                            ("DEP", "Deposito"),
                            ("ADM", "Administracion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("importe", models.FloatField()),
            ],
        ),
    ]
